### ISSUE TITLE
refactor: SWR을 적용하여 성능 개선 

### ISSUE THREAD

**Issue by gitul0515** [prgrms-fe-devcourse/FEDC2_GreenButler_Off#212]
### 기능 이슈

SWR을 도입하여 
'메인페이지', '게시물 상세 페이지'의 성능을 개선합니다. 

두 페이지에서 사용하는 API의 성능이 상당히 느립니다. 
예를 들어, 5개의 게시물을 불러오는 데 약 0.8s 가량 소요됩니다. 
이 때문에 페이지의 전환 속도가 꽤 느립니다. 

SWR의 '캐싱 전략'과 '프리패칭'을 통해서 이를 보완할 생각입니다. 
댓글 UI에도 SWR을 적용하여 서버와의 동기화를 높입니다. 
그 외 무한스크롤 시 Spinner를 추가합니다. 

- [ ] SWR 전역 옵션 설정
- [ ] 캐시 적용 (Main, PostDetail)
- [ ] 데이터 프리패칭 (PostDetail)
- [ ] 댓글 데이터의 실시간 갱신 (PostDetail)
- [ ] 무한스크롤 시 Spinner 추가 (Main)

**Comment by bellasimi** [comment]
이거 리액트 쿼리랑 비슷하네요 👀 이런 훅이 있는 줄은 몰랐는데, 좋은 공부가 됐습니다.

**Comment by gitul0515** [comment]
넵, 캐싱을 사용한다는 점에서 SWR과 React Query는 유사하지요. 
도움이 되셨다니 다행이네요 :)
